<a href="https://colab.research.google.com/github/priyal6/Featureengineering/blob/main/Ordinal_Encoding_and_Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

age  gender review education purchased
10   98  Female   Good        UG       Yes
31   22  Female   Poor    School       Yes
27   69  Female   Poor        PG        No
14   15    Male   Poor        PG       Yes
28   48    Male   Poor    School        No

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size = 0.2)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
X_train

review education
11     Good        UG
29  Average        UG
13  Average    School
4   Average        UG
26     Poor        PG
47     Good        PG
18     Good    School
5   Average    School
49     Good        UG
33     Good        PG
36     Good        UG
23     Good    School
43     Poor        PG
39     Poor        PG
44  Average        UG
7      Poor    School
1      Poor        UG
17     Poor        UG
8   Average        UG
34  Average    School
35     Poor    School
25     Good    School
24  Average        PG
15     Poor        UG
19     Poor        PG
20  Average    School
27     Poor        PG
30  Average        UG
31     Poor    School
48     Good        UG
28     Poor    School
32  Average        UG
9      Good        UG
40     Good    School
0   Average    School
12     Poor    School
2      Good        PG
3      Good        PG
42     Good        PG
16     Poor        UG

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train = oe.transform(X_train)

In [13]:
X_train

array([[2., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
X_train

array([[2., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [19]:
le.fit(y_train)

LabelEncoder()

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:
y_train

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1])